services:
  app:
    build:
      context: .
      dockerfile: docker/app/develop.Dockerfile
    tty: true
    volumes:
      - .:/application
    ports:
      # - 3002:3002 # frontend
      - 4943:4943 # icp
