/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/t_ecdsa.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface t_ecdsaInterface {
    getEvmAddress(): Promise<string>;
    getNewPublicKey(): Promise<string>;
    getPublicKey(): Promise<string>;
    signWithEcdsa(arg0: string): Promise<string>;
    signWithEthereum(mesage: string): Promise<string>;
    signWithEvmWallet(arg0: Uint8Array): Promise<string>;
    verifyWithEcdsa(arg0: {
        signature: string;
        publicKey: string;
        message: string;
    }): Promise<boolean>;
    verifyWithEthereum(arg0: {
        signature: string;
        message: string;
        ethereumAddress: string;
    }): Promise<boolean>;
}
export class T_ecdsa implements t_ecdsaInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async getEvmAddress(): Promise<string> {
        const result = await this.actor.getEvmAddress();
        return result;
    }
    async getNewPublicKey(): Promise<string> {
        const result = await this.actor.getNewPublicKey();
        return result;
    }
    async getPublicKey(): Promise<string> {
        const result = await this.actor.getPublicKey();
        return result;
    }
    async signWithEcdsa(arg0: string): Promise<string> {
        const result = await this.actor.signWithEcdsa(arg0);
        return result;
    }
    async signWithEthereum(arg0: string): Promise<string> {
        const result = await this.actor.signWithEthereum(arg0);
        return result;
    }
    async signWithEvmWallet(arg0: Uint8Array): Promise<string> {
        const result = await this.actor.signWithEvmWallet(arg0);
        return result;
    }
    async verifyWithEcdsa(arg0: {
        signature: string;
        publicKey: string;
        message: string;
    }): Promise<boolean> {
        const result = await this.actor.verifyWithEcdsa(arg0);
        return result;
    }
    async verifyWithEthereum(arg0: {
        signature: string;
        message: string;
        ethereumAddress: string;
    }): Promise<boolean> {
        const result = await this.actor.verifyWithEthereum(arg0);
        return result;
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): T_ecdsa {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new T_ecdsa(actor);
}
